# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('firstName', models.CharField(max_length=1024)),
                ('lastName', models.CharField(max_length=1024)),
                ('notes', models.CharField(max_length=1024)),
                ('weight', models.IntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
