# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20161005_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='extra',
        ),
    ]
